### ISSUE TITLE
alpine home dir

### ISSUE THREAD

**Issue by robertschoenthal1337** [felixb/swamp#12]
`Error initializing profile writer: Error fetching home dir: user: Current not implemented on linux/amd64`

`whoami` :`root` 
`ls ~` : `/root/...` 

what went wrong?

**Comment by felixb** [comment]
you need to set the `USER` environment variable inside the docker container to make swamp find your home dir.

just pass it to `docker run` like this:
```
docker run -ti --rm -e USER=root -v $PWD/swamp_alpine:/bin/swamp:ro -v $HOME/.aws:/root/.aws:ro alpine swamp ....
```
