### ISSUE TITLE
Mac OS - Support for installation via HomeBrew Cask

### ISSUE THREAD

**Issue by mechastorm** [felixb/swamp#17]
This is great tool! Makes it great to interacting with AWS Tools that do not yet recognize shared credentials and need explicit access/secret key.

I was wondering if you have considering put it up as a official [brew cask formula](https://github.com/Homebrew/homebrew-cask). This is so that it simplifies installation for Mac OS users to just be `brew cask install swamp`.

If it hasn't been considered yet I don't mind adding in formula myself to enable this.

**Comment by felixb** [comment]
I'm not eager to support any packages. There is already some guy supporting arch linux.
Feel free to support macOS yourself. You may want to update the `README.md` with a hint.
