### ISSUE TITLE
swamp should not rely on stdin

### ISSUE THREAD

**Issue by toralf-hlag** [felixb/swamp#20]
Hi
the following code snippet won't work:
```
while read line
do
  read -r id name <<< ${line}
  swamp -profile "<snip>" -mfa-device "<snip>" -account "${id}" -target-role "${role}" -target-profile "<snip>"
done <<-EOL
123456789012 account-name
EOL
```
Swamp seems to read from the same input stream as the while loop is doing.
Whilst we found a work around I do wonder why swamp doesn't use another file descriptor for the MFA token?

**Comment by felixb** [comment]
How would swamp read user input from other FD than `stdin`?
You could make use of the `-mfa-exec` option to force swamp not to read from `stdin`.
You could also pipe some other FD or file into swamp in your code.

**Comment by felixb** [comment]
timeout.
