### ISSUE TITLE
Install swamp via brew on Mac

### ISSUE THREAD

**Issue by splieth** [felixb/swamp#22]
Even though you most likely won’t consider MacOS as a real operating system: I was tired of installing swamp manually, so I created a custom tap for brew. Would you mind having it in ze Readme so others can make use of it as well?

**Comment by felixb** [comment]
Well. There is a `swamp.exe`. So much for real OSs.
Anyway, as I stated in #17 already: feel free to host your brew stuff and modify the `README.md`.
