### ISSUE TITLE
Is it possible to get the AWS_PROFILE export into the current shell back with yaml alias generation?

### ISSUE THREAD

**Issue by christianplatta1012** [felixb/swamp#29]
Hi,
as far as I understood, it is not possible to export the AWS_PROFILE in the current shell that executed the swamp command. 
The exec command is executed in a new /bin/sh shell and cannot set environment variables in the parent shell. Even sourcing a script in exec does not work. I think this is because the go process itself is not able to changed env vars in the shell that called swamp. 
Am I missing something? Can this still be done like in version 0.11.0 with -export-profile and -export-file ?
The yaml config alias generation is useful but I don't see a way to emulate the -export-profile behavior with this.
Sometimes we don't want to spawn a new shell just for swamping. You get a lot of nested shells when you switch between multiple accounts a lot which is annoying. Having both options (new shell vs. use current shell) would be nice.

Best regards,
Christian

**Comment by felixb** [comment]
The feature was dropped intentionally. A lot of people complained to me about swamp not working, but actually it was a misused by setting the target AWS_PROFILE outside and thus preventing swamp from running a second time.
95% of "swamp does not work" problems are resolved by me shouting w/o looking `unset AWS_PROFILE`.

That said: processes spawned can never change the environment of parents. That's just plain UNIX.
If you really want to emulate the old behavior, just create an alias/function like this:

```bash
function swamp_with_export() {
  swamp [..] -target-profile whatever-profile
  export AWS_PROFILE=whatever-profile
}
```
