### ISSUE TITLE
Support for AWS_* Environment Variables to choose Source Credentials

### ISSUE THREAD

**Issue by digitalkaoz** [felixb/swamp#7]
`swamp` without `-profile` should look for (in this order)

`AWS_PROFILE`

`AWS_ACCESS_KEY_ID`
`AWS_SECRET_ACCESS_KEY` 
`AWS_SESSION_TOKEN`

`default`

for choosing the input credentials to assume the specified role

**Comment by felixb** [comment]
Use the `-instance` flag to get the described behavior.
The naming is kind of strange. It is what you're looking for, though.
